name: 'Maven CLI for GitHub Actions with JDK 11'
description: 'Use Maven CLI with JDK 11'
branding:
    icon: package
    color: green
inputs:
    lifecycle:
        description: 'Maven lifecycles'
        required: true
        default: 'clean package'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.lifecycle }}
